name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      GIT_COMMIT_HASH: ${{ github.sha }}
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: SNIFS-science/https://github.com/SNIFS-science/prefect-hpc-worker/image
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ghcr.io
        cache: true
        buildargs: GIT_COMMIT_HASH